# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='ticket_colour',
            new_name='ticket_color',
        ),
        migrations.RemoveField(
            model_name='diarypage',
            name='when_happened',
        ),
    ]
