# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_auto_20170804_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarypage',
            name='text_rich',
            field=models.TextField(),
        ),
    ]
