# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 10:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_auto_20170809_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diarypage',
            name='title',
        ),
    ]
