# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-07 11:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='b',
        ),
    ]
