# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-17 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_likers'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(height_field=100, null=True, upload_to='/article', width_field=100),
        ),
    ]
