# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-27 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20161222_2001'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Likers',
            new_name='Likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
