# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-28 07:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20161227_1659'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Likes',
            new_name='Liker',
        ),
    ]
