# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20161228_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikesManger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
