# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 07:40
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_likesmanger'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text_rich',
            field=ckeditor.fields.RichTextField(blank=True, default=''),
        ),
    ]
