# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-17 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lowMes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='name',
            field=models.CharField(default='h', max_length=40),
            preserve_default=False,
        ),
    ]
